direction: down

container: {
  label: ""

  ram: {
    label: group
    label.near: top-center
    grid-rows: 1
    grid-gap: 0
    width: 800

    **: {
      label: ''
      width: 100
      style: {
        fill-pattern: lines
        double-border: true
      }
    }

    0
    0.style: {
      double-border: true
    }
    1
    2
    3
    4
    5
    6
    7
  }
}
