...@vars

direction: right

vars: {
  d2-config: {
    theme-id: 0
    pad: 0
    center: true
    sketch: true
    layout-engine: elk

    theme-overrides: {
      B1: "#000000" # arrow color
      N2: "#000000" # italic color
    }
  }
}

style: {
  fill: transparent
  font-size: 8
}

# Default style
*: {
  label: ""
  label.near: top-left
}
**: {
  shape: rectangle
  class: orange
}

# #

auth0: {
  user -> auth0: generate a\n token

  title: {
    label: Auth0 Environment
  }

  user: {
    shape: image
    icon: ${user-icon}
    label: User
  }

  auth0: {
    shape: image
    icon: ${auth0-icon}
    label: Auth0
  }
}

apis: APIs {
  label: APIs

  hub: {
    label: Api Hub
    shape: image
    icon: ${api-icon}
  }

  alerting: {
    label: Alerting
    class: green

    validate: {
      shape: image
      label: Needs to validate token
      icon: ${loading-icon}
    }

    api: {
      shape: image
      label: API\nAlerting
      icon: ${api-icon}
    }

    validate -> api
  }

  textreveal: {
    label: TextReveal
    class: blue

    validate: {
      shape: image
      label: Needs to validate token
      icon: ${loading-icon}
    }

    api: {
      shape: image
      label: API\nTextReveal
      icon: ${api-icon}
    }

    validate -> api
  }

  hub -> alerting
  hub -> textreveal
}

auth0 -> apis.hub: use a single\ntoken
