vars: {
  d2-config: {
    theme-id: 0
    pad: 0
    layout-engine: dagre

    theme-overrides: {
      B1: "#000000" # arrow color
      N2: "#000000" # italic color
    }
  }
}

vars: {
  loading-icon: https://cdn.hugeicons.com/icons/loading-03-stroke-rounded.svg
  user-icon: https://app.eraser.io/static/canvas-icons/user.svg
  api-icon: https://cdn.hugeicons.com/icons/api-stroke-rounded.svg
  auth0-icon: https://img.icons8.com/?size=80&id=wolE63GuuT9v&format=png

  colors: {
    greeen: {
      light: "#F7FDF9"
      dark: "#A9D8B7"
    }
    orange: {
      light: "#FDFBF6"
      dark: "#D9B073"
    }
    blue: {
      light: "#F7F9FD"
      dark: "#8CADDD"
    }
    purple: {
      light: "#FCF7FD"
      dark: "#DA85E0"
    }
    red: {
      light: "#FDF7F7"
      dark: "#D88F8A"
    }
  }
}

classes: {
  green: {
    style: {
      stroke: ${colors.greeen.dark}
      fill: ${colors.greeen.light}
    }
  }
  orange: {
    style: {
      stroke: ${colors.orange.dark}
      fill: ${colors.orange.light}
    }
  }
  blue: {
    style: {
      stroke: ${colors.blue.dark}
      fill: ${colors.blue.light}
    }
  }
  purple: {
    style: {
      stroke: ${colors.purple.dark}
      fill: ${colors.purple.light}
    }
  }
  red: {
    style: {
      stroke: ${colors.red.dark}
      fill: ${colors.red.light}
    }
  }
  label: {
    label.near: top-left
    style: {
      fill: white
    }
  }
  container: {
    shape: rectangle
    style: {
      border-radius: 10
    }
  }
}
