direction: down

vars: {
  d2-config: {
    theme-id: 0
    layout-engine: elk
  }
}

classes: {
  green: {
    style: {
      stroke: ${colors.greeen.dark}
      fill: ${colors.greeen.light}
    }
  }
  orange: {
    style: {
      stroke: ${colors.orange.dark}
      fill: ${colors.orange.light}
    }
  }
  blue: {
    style: {
      stroke: ${colors.blue.dark}
      fill: ${colors.blue.light}
    }
  }
  purple: {
    style: {
      stroke: ${colors.purple.dark}
      fill: ${colors.purple.light}
    }
  }
  red: {
    style: {
      stroke: ${colors.red.dark}
      fill: ${colors.red.light}
    }
  }
  label: {
    label.near: top-left
    style: {
      fill: white
    }
  }
  container: {
    shape: rectangle
    style: {
      border-radius: 10
    }
  }
}
