vars: {
  loading-icon: https://cdn.hugeicons.com/icons/loading-03-stroke-rounded.svg
  user-icon: https://app.eraser.io/static/canvas-icons/user.svg
  api-icon: https://cdn.hugeicons.com/icons/api-stroke-rounded.svg
  auth0-icon: https://img.icons8.com/?size=80&id=wolE63GuuT9v&format=png

  colors: {
    greeen: {
      light: "#F7FDF9"
      dark: "#A9D8B7"
    }
    orange: {
      light: "#FDFBF6"
      dark: "#D9B073"
    }
    blue: {
      light: "#F7F9FD"
      dark: "#8CADDD"
    }
    purple: {
      light: "#FCF7FD"
      dark: "#DA85E0"
    }
    red: {
      light: "#FDF7F7"
      dark: "#D88F8A"
    }
  }
}

style: {
  fill: transparent
}

# Arrow from root to any deep
(* -> **)[*]: {
  style: {
    stroke: "#000000"
    font-color: "#000000"
  }
}
